# Generated by Django 6.0.1 on 2026-01-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('tp1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ltp1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ltp2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ltp3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateField()),
                ('mtp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('loss_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_recent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pl_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True)),
                ('max_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
