COMPANY_NAMES = {
    "PSO"       : "Pakistan State Oil",
    "OGDC"      : "Oil & Gas Development Company Limited",
    "PPL"       : "Pakistan Petroleum Limited",
    "HUBC"      : "Hub Power Company Limited",
    "ENGRO"     : "Engro Corporation Limited",
    "FFC"       : "Fauji Fertilizer Company Limited",
    "GAL"       : "Ghani Automobile Industries Limited",
    "AKBLTFC6"  : "Askari Bank (TFC 6)",
    "BAFLTFC6"  : "Bank Al-Falah (TFC 6)",
    "BAFLTFC8"  : "Bank Alfalah (TFC 8)",
    "BAHLTFC10" : "Bank AL HABIB LTD (TFC 10)",
    "BAHLTFC9"  : "Bank Al-Habib (TFC 9)",
    "BCEMSTSC"  : "BCEM Sukuk",
    "BIPLSC"    : "Bank Islami SC",
    "BIPLSC2"   : "Bank Islami Sukuk 2",
    "BOPTFC2"   : "Bank of Punjab (TFC 2)",
    "HBLTFC2"   : "Habib Bank (TFC 2)",
    "HBLTFC3"   : "Habib Bank (TFC 3)",
    "HUBPHLSC"  : "Hub Power Holding Sukuk",
    "JSBLTFC2"  : "JS Bank Ltd (TFC 2)",
    "JSBLTFC3"  : "JS Bank (TFC 3)",
    "JSBLTFC4"  : "JS Bank (TFC 4)",
    "KELSC5"    : "K-Electric (SUKUK 5)",
    "KELSC6"    : "K-Electric Ltd (SUKUK 6)",
    "KELSTSC"   : "KE Short Term Sukuk",
    "KFGB1"     : "Kashf Gender Bond",
    "LOADSSTSC" : "Loads Short Term Sukuk",
    "MMBLTFC"   : "Mobilink TFC",
    "MUGHALSC"  : "Mughal Steel Sukuk",
    "MUGHALSTSC": "Mughal Short Term Sukuk",
    "PFCSTSC"   : "Pakistan Finance Short Term Sukuk",
    "QATRSTSC"  : "Qatar Investment Sukuk",
    "SBPSTSC"   : "SBP Short Term Sukuk",
    "SBPSTSC2"  : "SBP Short Term Sukuk 2",
    "SBPSTSC3"  : "SBP Short Term Sukuk 3",
    "SBPSTSC4"  : "SBP Short Term Sukuk 4",
    "SBPSTSC5"  : "SBP Short Term Sukuk 5",
    "SBPSTSC6"  : "SBP Short Term Sukuk 6",
    "SBPSTSC7"  : "SBP Short Term Sukuk 7",
    "SBPSTSC8"  : "SBP Short Term Sukuk 8",
    "SBPSTSC9"  : "SBP Short Term Sukuk 9",
    "SBPSTSC10" : "SBP Short Term Sukuk 10",
    "AGTL"      : "AL-Ghazi Tractors",
    "ATLH"      : "Atlas Honda Ltd",
    "DFML"      : "Dewan Motors",
    "GAL"       : "Ghandhara Automobile",
    "GHNI"      : "Ghandhara Ind.",
    "HCAR"      : "Honda Atlas Cars",
    "HINO"      : "Hinopak Motor",
    "INDU"      : "Indus Motor Co.",
    "MTL"       : "Millat Tractors",
    "SAZEW"     : "Sazgar Engineering",
    "AGIL"      : "Agriautos Ind.",
    "ATBA": "Atlas Battery",
    "BELA": "Bela Automotive",
    "BWHL": "Bal.Wheels",
    "DWAE": "Dewan Auto Engg",
    "EXIDE": "Exide (PAK)",
    "GTYR": "Ghandhara Tyre",
    "LOADS": "Loads Limited",
    "PTL": "Panther Tyres Ltd.",
    "TBL": "Treet Battery Ltd.",
    "THALL": "Thal Limited",
    "EMCO": "EMCO Industries",
    "FCL": "Fast Cables Ltd.",
    "PAEL": "Pak Elektron",
    "PCAL": "Pakistan Cables-",
    "SIEM": "Siemens Pak.",
    "WAVES": "Waves Corp Ltd.",
    "WAVESAPP": "Waves Home App",
    "ACPL": "Attock Cement",
    "BWCL": "Bestway Cement",
    "CHCC": "Cherat Cement",
    "DBCI": "Dadabhoy Cement",
    "DCL": "Dewan Cement",
    "DGKC": "D.G.K.Cement",
    "DNCC": "Dandot Cement",
    "FCCL": "Fauji Cement",
    "FECTC": "Fecto Cement",
    "FLYNG": "Flying Cement",
    "GWLC": "Gharibwal Cement",
    "KOHC": "Kohat Cement",
    "LUCK": "Lucky Cement",
    "MLCF": "Maple Leaf",
    "PIOC": "Pioneer Cement",
    "POWER": "Power Cement",
    "POWERPS": "Power Cem(Pref)",
    "SMCPL": "Safe Mix Con.Ltd",
    "THCCL": "Thatta Cement",
    "ZELP": "Zeal Pak.",
    "AGLNCPS": "Agritechn-v(PRE",
    "ARPL": "Archroma Pak",
    "BAPL": "Bawany Air Prod",
    "BERG": "Berger Paints",
    "BIFO": "Biafo Industries",
    "BUXL": "Buxly Paints",
    "DAAG": "Data Agro",
    "DOL": "Descon Oxychem",
    "DYNO": "Dynea Pakistan",
    "EPCL": "Engro Polymer",
    "EPCLPS": "Engro Poly (Pref)",
    "GCIL": "Ghani Chemical",
    "GCWL": "Ghani Chemworld",
    "GGL": "Ghani Glo Hol",
    "ICL": "Ittehad Chemicals",
    "LCI": "Lucky Core Ind.",
    "LOTCHEM": "Lotte Chemical",
    "LPGL": "Leiner Pak Gelat",
    "NICL": "Nimir Ind.Chem",
    "NRSL": "Nimir Resins",
    "PAKOXY": "Pak Oxygen Ltd.",
    "PPVC": "Pak.P.V.C.",
    "SARC": "Sardar Chemical",
    "SHCI": "Shaffi Chemical",
    "SITC": "Sitara Chemical",
    "SPL": "Sitara Peroxide",
    "WAHN": "Wah-Noble",
    "HGFA": "HBL Growth Fund",
    "HIFA": "HBL Invest Fund",
    "INMF": "Inv. Mutual Fund",
    "PUDF": "P.S.Fund",
    "TSMF": "Tri-Star Mutual",
    "ABL": "Allied Bank Ltd",
    "AKBL": "Askari Bank",
    "BAFL": "Bank Al-Falah",
    "BAHL": "Bank AL-Habib",
    "BIPL": "Bankislami Pak",
    "BML": "Bank Makramah",
    "BOK": "Bank Of Khyber",
    "BOP": "B.O.Punjab",
    "FABL": "Faysal Bank",
    "HBL": "Habib Bank",
    "HMB": "Habib Metropolitan",
    "JSBL": "JS Bank Ltd",
    "MCB": "MCB Bank Ltd",
    "MEBL": "Meezan Bank Ltd",
    "NBP": "National BankXD",
    "SBL": "Samba Bank",
    "SCBPL": "St.Chart.Bank",
    "SNBL": "Soneri Bank Ltd",
    "UBL": "United Bank",
    "AGHA": "Agha Steel Ind.",
    "ASL": "Aisha Steel Mill",
    "ASLCPS": "Aisha Steel(CPS)",
    "ASLPS": "Aisha StelCoP/S",
    "ASTL": "Amreli Steels",
    "BCL": "Bolan Casting",
    "BECO": "Beco Steel Ltd",
    "CSAP": "Crescent Steel",
    "DADX": "Dadex Eternit",
    "DSL": "Dost Steels Ltd.",
    "HSPI": "Huffaz Seamless",
    "INIL": "Int. Ind.Ltd.",
    "ISL": "Inter.Steel Ltd",
    "ITTEFAQ": "Ittefaq Iron Ind",
    "KSBP": "K.S.B.Pumps",
    "MSCL": "Metro Steel",
    "MUGHAL": "Mughal Iron",
    "MUGHALC": "Mughal Iron(C)",
    "PECO": "Pak Engineering",
    "ACIETF": "Alfalah Consumer",
    "HBLTETF": "HBL Total Treasury",
    "JSGBETF": "JS Global Banking",
    "JSMFETF": "JS MomentumXD",
    "MIIETF": "Mahaana Islamic",
    "MZNPETF": "Meezan Pakistan",
    "NBPGETF": "NBP Pakistan G ETF",
    "NITGETF": "NIT Pakistan",
    "UBLPETF": "UBLPakistanETF",
    "AGL": "Agritech Limited",
    "AHCL": "Arif Habib Corp",
    "EFERT": "Engro Fertert",
    "FATIMA": "Fatima Fert",
    "FFC": "Fauji Fert",
    "ASC": "Al-Shaheer Corp",
    "BBFL": "Big Bird Foods Ltd.",
    "BFAGRO": "Barkat Frisian Agro",
    "BNL": "Bunnys Limited",
    "CLOV": "Clover Pakistan",
    "COLG": "Colgate Palm",
    "FCEPL": "Frieslandcampina",
    "FFL": "Fauji Foods Ltd",
    "GIL": "Goodluck Ind.",
    "GLPL": "Gillette Pak",
    "ISIL": "Ismail Ind.",
    "MFFL": "MithchellsFruit",
    "MFL": "Matco Foods Ltd",
    "MUREB": "Murree Brewery",
    "NATF": "National Foods",
    "NESTLE": "Nestle Pakistan",
    "NMFL": "Nirala MSR Food",
    "PREMA": "At-Tahur Ltd.",
    "QUICE": "Quice Food",
    "RMPL": "Rafhan Maize",
    "SCL": "Shield Corp.",
    "SHEZ": "Shezan Inter.",
    "TOMCL": "The Organic Meat",
    "TREET": "Treet Corp",
    "UNITY": "Unity Foods Ltd",
    "UPFL": "Unilever Foods",
    "ZIL": "ZIL Limited",
    "AGHA-FEB": "Agha Steel Ind.",
    "AGHA-JAN": "Agha Steel Ind.",
    "AGHA-MAR": "Agha Steel Ind.",
    "AGL-FEB": "Agritech Limited",
    "AGL-JAN": "Agritech Limited",
    "AGL-MAR": "Agritech Limited",
    "AGP-FEB": "AGP Limited",
    "AGP-JAN": "AGP Limited",
    "AGP-MAR": "AGP Limited",
    "AICL-FEB": "Adamjee Ins.",
    "AICL-JAN": "Adamjee Ins.",
    "AICL-MAR": "Adamjee Ins.",
    "AIRLINK-FEB": "Air Link Commun",
    "AIRLINK-JAN": "Air Link Commun",
    "AIRLINK-MAR": "Air Link Commun",
    "AKBL-FEB": "Askari Bank",
    "AKBL-JAN": "Askari Bank",
    "AKBL-MAR": "Askari Bank",
    "ASL-FEB": "Aisha Steel Mill",
    "ASL-JAN": "Aisha Steel Mill",
    "ASL-MAR": "Aisha Steel Mill",
    "ATRL-FEB": "Attock Refinery",
    "ATRL-JAN": "Attock Refinery",
    "ATRL-MAR": "Attock Refinery",
    "AVN-FEB": "Avanceon Ltd",
    "AVN-JAN": "Avanceon Ltd",
    "AVN-MAR": "Avanceon Ltd",
    "BAFL-FEB": "Bank Al-Falah",
    "BAFL-JAN": "Bank Al-Falah",
    "BAFL-MAR": "Bank Al-Falah",
    "BAHL-FEB": "Bank AL-Habib",
    "BAHL-JAN": "Bank AL-Habib",
    "BAHL-MAR": "Bank AL-Habib",
    "BIPL-FEB": "Bankislami Pak",
    "BIPL-JAN": "Bankislami Pak",
    "BIPL-MAR": "Bankislami Pak",
    "BML-FEB": "Bank Makramah",
    "BML-JAN": "Bank Makramah",
    "BML-MAR": "Bank Makramah",
    "BOP-FEB": "B.O.Punjab",
    "BOP-JAN": "B.O.Punjab",
    "BOP-MAR": "B.O.Punjab",
    "CHCC-FEB": "Cherat Cement",
    "CHCC-JAN": "Cherat Cement",
    "CHCC-MAR": "Cherat Cement",
    "CNERGY-FEB": "Cnergyico PK",
    "CNERGY-JAN": "Cnergyico PK",
    "CNERGY-MAR": "Cnergyico PK",
    "CPHL-FEB": "Citi Pharma Ltd",
    "CPHL-JAN": "Citi Pharma Ltd",
    "CPHL-MAR": "Citi Pharma Ltd",
    "CSAP-FEB": "Crescent Steel",
    "CSAP-JAN": "Crescent Steel",
    "CSAP-MAR": "Crescent Steel",
    "DCL-FEB": "Dewan Cement",
    "DCL-JAN": "Dewan Cement",
    "DCL-MAR": "Dewan Cement",
    "DCR-FEBB": "Dolmen City",
    "DCR-JANB": "Dolmen City",
    "DCR-MAR": "Dolmen City",
    "DFML-FEB": "Dewan Motors",
    "DFML-JAN": "Dewan Motors",
    "DGKC-FEB": "D.G.K.Cement",
    "DGKC-JAN": "D.G.K.Cement",
    "DGKC-MAR": "D.G.K.Cement",
    "EFERT-FEB": "Engro Fertert",
    "EFERT-JAN": "Engro Fertert",
    "EFERT-MAR": "Engro Fertert",
    "ENGROH-FEB": "Engro Holdings",
    "ENGROH-JAN": "Engro Holdings",
    "ENGROH-MAR": "Engro Holdings",
    "EPCL-FEB": "Engro Polymer",
    "EPCL-JAN": "Engro Polymer",
    "EPCL-MAR": "Engro Polymer",
    "FABL-FEB": "Faysal Bank",
    "FABL-JAN": "Faysal Bank",
    "FABL-MAR": "Faysal Bank",
    "FATIMA-FEB": "Fatima Fert",
    "FATIMA-JAN": "Fatima Fert",
    "FATIMA-MAR": "Fatima Fert",
    "FCCL-FEB": "Fauji Cement",
    "FCCL-JAN": "Fauji Cement",
    "FCCL-MAR": "Fauji Cement",
    "FCEPL-FEB": "Frieslandcampina",
    "FCEPL-JAN": "Frieslandcampina",
    "FCEPL-MAR": "Frieslandcampina",
    "FCL-FEB": "Fast Cables Ltd.",
    "FCL-JAN": "Fast Cables Ltd.",
    "FCL-MAR": "Fast Cables Ltd.",
    "FFC-FEB": "Fauji Fert",
    "FFC-JAN": "Fauji Fert",
    "FFC-MAR": "Fauji Fert",
    "FFL-FEB": "Fauji Foods Ltd",
    "FFL-JAN": "Fauji Foods Ltd",
    "FFL-MAR": "Fauji Foods Ltd",
    "FLYNG-FEB": "Flying Cement",
    "FLYNG-JAN": "Flying Cement",
    "FLYNG-MAR": "Flying Cement",
    "GAL-FEB": "Ghandhara Automobile",
    "GAL-JAN": "Ghandhara Automobile",
    "GAL-MAR": "Ghandhara Automobile",
    "GATM-FEB": "Gul Ahmed",
    "GATM-JAN": "Gul Ahmed",
    "GATM-MAR": "Gul Ahmed",
    "GCIL-FEB": "Ghani Chemical",
    "GCIL-JAN": "Ghani Chemical",
    "GCIL-MAR": "Ghani Chemical",
    "GGL-FEB": "Ghani Glo Hol",
    "GGL-JAN": "Ghani Glo Hol",
    "GGL-MAR": "Ghani Glo Hol",
    "GHGL-FEB": "Ghani Glass Ltd",
    "GHGL-JAN": "Ghani Glass Ltd",
    "GHGL-MAR": "Ghani Glass Ltd",
    "GHNI-FEB": "Ghandhara Ind.",
    "GHNI-JAN": "Ghandhara Ind.",
    "GHNI-MAR": "Ghandhara Ind.",
    "GLAXO-FEB": "GlaxoSmithKline",
    "GLAXO-JAN": "GlaxoSmithKline",
    "GLAXO-MAR": "GlaxoSmithKline",
    "HBL-FEB": "Habib Bank",
    "HBL-JAN": "Habib Bank",
    "HBL-MAR": "Habib Bank",
    "HUBC-FEB": "Hub Power Co.",
    "HUBC-JAN": "Hub Power Co.",
    "HUBC-MAR": "Hub Power Co.",
    "HUMNL-FEB": "Hum Network",
    "HUMNL-JAN": "Hum Network",
    "HUMNL-MAR": "Hum Network",
    "ILP-FEB": "Interloop Ltd.",
    "ILP-JAN": "Interloop Ltd.",
    "ILP-MAR": "Interloop Ltd.",
    "IMAGE-FEB": "Image Pakistan",
    "IMAGE-JAN": "Image Pakistan",
    "IMAGE-MAR": "Image Pakistan",
    "INIL-FEB": "Int. Ind.Ltd.",
    "INIL-JAN": "Int. Ind.Ltd.",
    "INIL-MAR": "Int. Ind.Ltd.",
    "ISL-FEB": "Inter.Steel Ltd",
    "ISL-JAN": "Inter.Steel Ltd",
    "ISL-MAR": "Inter.Steel Ltd",
    "JSGBETF-FEB": "JS Global Banking",
    "JSGBETF-JAN": "JS Global Banking",
    "JSGBETF-MAR": "JS Global Banking",
    "JSMFETF-FEBB": "JS MomentumXD",
    "JSMFETF-JANB": "JS MomentumXD",
    "JSMFETF-MARB": "JS MomentumXD",
    "KAPCO-FEB": "Kot Addu Power",
    "KAPCO-JAN": "Kot Addu Power",
    "KAPCO-MAR": "Kot Addu Power",
    "KEL-FEB": "K-Electric Ltd.",
    "KEL-JAN": "K-Electric Ltd.",
    "KEL-MAR": "K-Electric Ltd.",
    "KOHC-FEB": "Kohat Cement",
    "KOHC-JAN": "Kohat Cement",
    "KOHC-MAR": "Kohat Cement",
    "KOSM-FEB": "Kohinoor Spining",
    "KOSM-JAN": "Kohinoor Spining",
    "KOSM-MAR": "Kohinoor Spining",
    "LOTCHEM-FEB": "Lotte Chemical",
    "LOTCHEM-JAN": "Lotte Chemical",
    "LOTCHEM-MAR": "Lotte Chemical",
    "LUCK-FEB": "Lucky Cement",
    "LUCK-JAN": "Lucky Cement",
    "LUCK-MAR": "Lucky Cement",
    "MARI-FEB": "Mari Energies Ltd.",
    "MARI-JAN": "Mari Energies Ltd.",
    "MARI-MAR": "Mari Energies Ltd.",
    "MCB-FEB": "MCB Bank Ltd",
    "MCB-JAN": "MCB Bank Ltd",
    "MCB-MAR": "MCB Bank Ltd",
    "MEBL-FEB": "Meezan Bank Ltd",
    "MEBL-JAN": "Meezan Bank Ltd",
    "MEBL-MAR": "Meezan Bank Ltd",
    "MLCF-FEB": "Maple Leaf",
    "MLCF-JAN": "Maple Leaf",
    "MLCF-MAR": "Maple Leaf",
    "MTL-FEB": "Millat Tractors",
    "MTL-JAN": "Millat Tractors",
    "MTL-MAR": "Millat Tractors",
    "MUGHAL-FEB": "Mughal Iron",
    "MUGHAL-JAN": "Mughal Iron",
    "MUGHAL-MAR": "Mughal Iron",
    "MZNPETF-FEB": "Meezan Pakistan",
    "MZNPETF-JAN": "Meezan Pakistan",
    "MZNPETF-MAR": "Meezan Pakistan",
    "NATF-FEB": "National Foods",
    "NATF-JAN": "National Foods",
    "NATF-MAR": "National Foods",
    "NBP-FEB": "National BankXD",
    "NBP-JAN": "National BankXD",
    "NBP-MAR": "National BankXD",
    "NBPGETF-FEB": "NBP Pakistan G ETF",
    "NBPGETF-JAN": "NBP Pakistan G ETF",
    "NBPGETF-MAR": "NBP Pakistan G ETF",
    "NCPL-FEB": "Nishat ChunPower",
    "NCPL-JAN": "Nishat ChunPower",
    "NCPL-MAR": "Nishat ChunPower",
    "NETSOL-FEB": "Netsol Tech.",
    "NETSOL-JAN": "Netsol Tech.",
    "NETSOL-MAR": "Netsol Tech.",
    "NITGETF-FEB": "NIT Pakistan",
    "NITGETF-JAN": "NIT Pakistan",
    "NITGETF-MAR": "NIT Pakistan",
    "NML-FEB": "Nishat Mills Ltd",
    "NML-JAN": "Nishat Mills Ltd",
    "NML-MAR": "Nishat Mills Ltd",
    "NPL-FEB": "Nishat Power",
    "NPL-JAN": "Nishat Power",
    "NPL-MAR": "Nishat Power",
    "NRL-FEB": "National Refinery",
    "NRL-JAN": "National Refinery",
    "NRL-MAR": "National Refinery",
    "OCTOPUS-JAN": "Octopus Digital",
    "OGDC-FEB": "Oil & Gas Dev",
    "OGDC-JAN": "Oil & Gas Dev",
    "OGDC-MAR": "Oil & Gas Dev",
    "PACE-FEB": "Pace (Pak) Ltd.",
    "PACE-JAN": "Pace (Pak) Ltd.",
    "PACE-MAR": "Pace (Pak) Ltd.",
    "PAEL-FEB": "Pak Elektron",
    "PAEL-JAN": "Pak Elektron",
    "PAEL-MAR": "Pak Elektron",
    "PIAHCLA-FEB": "PIA Holding Company",
    "PIAHCLA-JAN": "PIA Holding Company",
    "PIAHCLA-MAR": "PIA Holding Company",
    "PIBTL-FEB": "Pak Int.Bulk",
    "PIBTL-JAN": "Pak Int.Bulk",
    "PIBTL-MAR": "Pak Int.Bulk",
    "PIOC-FEB": "Pioneer Cement",
    "PIOC-JAN": "Pioneer Cement",
    "PIOC-MAR": "Pioneer Cement",
    "POL-FEB": "Pak Oilfields",
    "POL-JAN": "Pak Oilfields",
    "POL-MAR": "Pak Oilfields",
    "POWER-FEB": "Power Cement",
    "POWER-JAN": "Power Cement",
    "POWER-MAR": "Power Cement",
    "PPL-FEB": "Pak Petroleum",
    "PPL-JAN": "Pak Petroleum",
    "PPL-MAR": "Pak Petroleum",
    "PREMA-FEB": "At-Tahur Ltd.",
    "PREMA-JAN": "At-Tahur Ltd.",
    "PREMA-MAR": "At-Tahur Ltd.",
    "PRL-FEB": "Pak Refinery",
    "PRL-JAN": "Pak Refinery",
    "PRL-MAR": "Pak Refinery",
    "PSO-FEB": "P.S.O.",
    "PSO-JAN": "P.S.O.",
    "PSO-MAR": "P.S.O.",
    "PTC-FEB": "P.T.C.L.",
    "PTC-JAN": "P.T.C.L.",
    "PTC-MAR": "P.T.C.L.",
    "SAZEW-FEB": "Sazgar Engineering",
    "SAZEW-JAN": "Sazgar Engineering",
    "SAZEW-MAR": "Sazgar Engineering",
    "SEARL-FEB": "The Searle Company",
    "SEARL-JAN": "The Searle Company",
    "SEARL-MAR": "The Searle Company",
    "SNBL-FEB": "Soneri Bank Ltd",
    "SNBL-JAN": "Soneri Bank Ltd",
    "SNBL-MAR": "Soneri Bank Ltd",
    "SNGP-FEB": "Sui North Gas",
    "SNGP-JANB": "Sui North Gas",
    "SNGP-MAR": "Sui North Gas",
    "SSGC-FEB": "Sui South Gas",
    "SSGC-JANB": "Sui South Gas",
    "SSGC-MAR": "Sui South Gas",
    "SYM-FEB": "Symmetry Group Ltd",
    "SYM-JAN": "Symmetry Group Ltd",
    "SYM-MAR": "Symmetry Group Ltd",
    "SYS-FEB": "Systems Limited",
    "SYS-JAN": "Systems Limited",
    "SYS-MAR": "Systems Limited",
    "TELE-FEB": "Telecard Limited",
    "TELE-JAN": "Telecard Limited",
    "TELE-MAR": "Telecard Limited",
    "TGL-FEB": "Tariq Glass Ind.",
    "TGL-JAN": "Tariq Glass Ind.",
    "TGL-MAR": "Tariq Glass Ind.",
    "THCCL-FEB": "Thatta Cement",
    "THCCL-JAN": "Thatta Cement",
    "THCCL-MAR": "Thatta Cement",
    "TOMCL-FEB": "The Organic Meat",
    "TOMCL-JAN": "The Organic Meat",
    "TOMCL-MAR": "The Organic Meat",
    "TPLP-FEB": "TPL Properties",
    "TPLP-JAN": "TPL Properties",
    "TPLP-MAR": "TPL Properties",
    "TREET-FEB": "Treet Corp",
    "TREET-JAN": "Treet Corp",
    "TREET-MAR": "Treet Corp",
    "TRG-FEB": "TRG Pak Ltd",
    "TRG-JAN": "TRG Pak Ltd",
    "TRG-MAR": "TRG Pak Ltd",
    "UBL-FEB": "United Bank",
    "UBL-JAN": "United Bank",
    "UBL-MAR": "United Bank",
    "UBLPETF-FEB": "UBLPakistanETF",
    "UBLPETF-JAN": "UBLPakistanETF",
    "UBLPETF-MAR": "UBLPakistanETF",
    "UNITY-FEB": "Unity Foods Ltd",
    "UNITY-JAN": "Unity Foods Ltd",
    "UNITY-MAR": "Unity Foods Ltd",
    "WAVES-FEB": "Waves Corp Ltd.",
    "WAVES-JAN": "Waves Corp Ltd.",
    "WAVES-MAR": "Waves Corp Ltd.",
    "WAVESAPP-FEB": "Waves Home App",
    "WAVESAPP-JAN": "Waves Home App",
    "WAVESAPP-MAR": "Waves Home App",
    "WTL-FEB": "WorldCall Telecom",
    "WTL-JAN": "WorldCall Telecom",
    "WTL-MAR": "WorldCall Telecom",
    "YOUW-JAN": "Yousuf Weaving",
    "BGL": "Bal.Glass",
    "FRCL": "Frontier Ceram",
    "GGGL": "GhaniGlobalGlass",
    "GHGL": "Ghani Glass Ltd",
    "GVGL": "Ghani Value Glass",
    "KCL": "Karam Ceramics",
    "REGAL": "Regal Ceramics",
    "STCL": "Shabbir Tiles",
    "AGIC": "Ask.Gen.Insurance",
    "AGICR2": "Ask.Gen.Ins.(R)",
    "AICL": "Adamjee Ins.",
    "ALAC": "Askari Life Ass",
    "ALIFE": "Adamjee Life Ass.",
    "ASIC": "Asia Insurance",
    "ATIL": "Atlas Ins. Ltd",
    "BIIC": "Business Insurance",
    "CENI": "Century Ins.",
    "CSIL": "Cres.Star Ins.XR",
    "EFUG": "EFU General",
    "EFUL": "EFU Life Assurance",
    "EWIC": "East West Insuranc",
    "HICL": "Habib Ins.",
    "IGIHL": "IGI Holdings",
    "IGIL": "IGI Life Ins",
    "JGICL": "Jubilee Gen.Ins",
    "JLICL": "Jubile Life Ins",
    "PAKQATAR": "Pak Qatar Family",
    "PAKRI": "Pak Reinsurance",
    "PIL": "PICIC Ins.Ltd.",
    "PINL": "Premier Ins.",
    "PKGI": "Pak Gen.Ins.",
    "PRIC": "Progressive Insuranc",
    "RICL": "Reliance Ins.",
    "SHNI": "Shaheen Ins.",
    "SSIC": "Silver Star Ins",
    "SWL": "Standard Worldwide",
    "TPLI": "TPL Insurance",
    "TPLL": "TPL Life Insurance",
    "UNIC": "United Insurance",
    "UVIC": "Universal Ins.",
    "786": "786 Invest Ltd",
    "786R": "786 Invest (R)",
    "AHL": "Arif Habib Ltd.",
    "AKDSL": "AKD Securites",
    "AMBL": "Apna Microfin.",
    "AMSL": "AL-Mal Sec.",
    "CASH": "Calcorp Limited",
    "CYAN": "Cyan Limited",
    "DEL": "Dawood Equities",
    "DHPL": "DH Partners Ltd.",
    "DLL": "Dawood Law",
    "ENGROH": "Engro Holdings",
    "ESBL": "Escorts Bank",
    "FCEL": "First Cap.Equit",
    "FCIBL": "F.Credit & Inv",
    "FCSC": "Ist.Capital Sec",
    "FDPL": "First Dawood Prop",
    "FNEL": "F. Nat.Equities",
    "ICIBL": "Invest Bank",
    "IML": "Imperial Limite",
    "IMS": "Intermarket Sec.",
    "JSCL": "Jah.Sidd. Co.",
    "JSCLPSA": "JahangirSidd(Pref)",
    "JSGCL": "JS Global Cap.",
    "JSIL": "JS Investments",
    "LSECL": "LSE Capital Ltd.",
    "LSEFSL": "LSE Fin. Services",
    "LSEVL": "LSE Ventures Ltd",
    "LSEVLR": "LSE Ventures(R)",
    "MCBIM": "MCB Inv MGT",
    "NEXT": "Next Capital",
    "OLPL": "OLP Financial",
    "PASL": "Pervez Ahmed Co",
    "PIAHCLA": "PIA Holding Company",
    "PIAHCLB": "PIA Holding CompanyB",
    "PRIB": "Prud.Inv.Bank",
    "PSX": "Pak Stock Exchange",
    "SIBL": "Sec. Inv. Bank",
    "TRIBL": "Trust Inv.Bank",
    "TSBL": "Trust Brokerage",
    "CJPL": "Crescent Jute",
    "SUHJ": "Suhail Jute",
    "ENGL": "English Leasing",
    "GRYL": "Grays Leasing",
    "PGLC": "Pak Gulf Leasing",
    "PICL": "Pak.Com.Leasing",
    "SLCL": "Security Leasin",
    "SLCPA": "Sec.Lea(Pr)9.1",
    "SLL": "SME Leasing Ltd",
    "SPCL": "Saudi Pak Consultanc",
    "BATA": "Bata (Pak) Ltd.",
    "FIL": "Fateh Industries",
    "LEUL": "Leather Up Ltd.",
    "PAKL": "Pak Leather",
    "SGF": "Service Global",
    "SRVI": "Service Ind.Ltd"

}
